version: "2"
services:
  mydemoreactimage:
    image: mydemoreactimage
    container_name: mydemoreactimage
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./frontend/react-docker:/app
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  dbdata:

